BasicGame={
	GAME_TITLE:document.title,
	MAIN_COLOR:'#c8f7f4',
	MAIN_TINT:0xc8f7f4,
	MAIN_TEXT_COLOR:'#28ceff',
	MAIN_STROKE_COLOR:'#7ed0e6',
	WHITE_COLOR:'#e9f0f4',
	YOUTUBE_URL:'https://www.youtube.com/channel/UCvmppcdYf4HOv-tFQhHHJMA',
	MY_GAMES_URL:'https://238g.github.io/Parace/238Games.html',
};
BasicGame.Boot=function(){};
BasicGame.Boot.prototype={
init:function(){this.M.BootInit(!1);},
preload:function(){this.load.crossOrigin='Anonymous';this.load.atlasJSONHash('loading','images/loading/loading.png','images/loading/loading.json');},
create:function(){
	this.M.defineConst({
		TOUCH_OR_CLICK: (this.game.device.touch)?'タッチ':'クリック',
		EN_TOUCH_OR_CLICK: (this.game.device.touch)?'TOUCH':'CLICK',
	});
	this.M.defineGlobal({
		endTut:!1,
		curStage:1,
	});
	this.M.defineConf({
		StageInfo:this.genStageInfo(),
		Words:this.genWords(),
		VehicleInfo:this.genVehicleInfo(),
		Vehicle:this.genVehicle(),
		ObstacleInfo:this.genObstacleInfo(),
	});
	this.M.NextScene('Preloader');
},};