BasicGame={
	GAME_TITLE:document.title,
	GAME_TITLE_EN:'YuNi-Game',
	MAIN_COLOR:'#ebfcac',
	MAIN_TINT:0xebfcac,
	MAIN_TEXT_COLOR:'#5bb1a0',
	MAIN_STROKE_COLOR:'#439587',
	WHITE_COLOR:'#ebe6e3',
	YOUTUBE_URL:'https://www.youtube.com/channel/UCHTnX0CSX_KObo5I9WuZ64g',
};
BasicGame.Boot=function(){};
BasicGame.Boot.prototype={
init:function(){this.M.BootInit(!1)},
preload:function(){this.load.atlasJSONHash('loading','images/loading/loading.png','images/loading/loading.json')},
create:function(){
	this.M.dGlb({
		curLang:'jp',
		// curLang:(this.M.H.getQuery('lang')=='en')?'en':'jp',
		playCount:0,
		endTut:!1,
		curLevel:1,
		Words:this.genWords(),
		LevelInfo:this.genLevelInfo(),
	});
	this.M.NextScene('Preloader');
},};