BasicGame.Boot.prototype.genWords=function(){
	return {
		jp:{
			Enter:'入り口',
			TitleDescription:
				'かなり恐ろしいことが起こります。\n'
				+'一度はじめてしまったら\n'
				+'腹をくくって最後まで\n'
				+'進むことをおすすめします。\n'
				+'命まで取らないのでご安心を。\n'
				+'覚悟が出来たら\n'
				+'中にお入りください。\n',
		},
		en:{
			Enter:'ENTER',
			TitleDescription:'',
		},
	};
};