BasicGame.Boot.prototype.genTargetInfo = function () {
	return {
		'Peanutkun_1': {
			name: 'Peanutkun_1',
			width: 84,
			height: 200,
			halfWidth: 42,
			halfHeight: 100,
			isTarget: true,
			scoreRate: 1.2,
		},
		'Peanutkun_2': {
			name: 'Peanutkun_2',
			width: 200,
			height: 161,
			halfWidth: 100,
			halfHeight: 80.5,
			isTarget: true,
			scoreRate: 1,
		},
		'Peanutkun_3': {
			name: 'Peanutkun_3',
			width: 83,
			height: 200,
			halfWidth: 41.5,
			halfHeight: 100,
			isTarget: true,
			scoreRate: 1.2,
		},
		'Peanutkun_4': {
			name: 'Peanutkun_4',
			width: 82,
			height: 200,
			halfWidth: 41,
			halfHeight: 100,
			isTarget: true,
			scoreRate: 1.2,
		},
		'Peanutkun_5': {
			name: 'Peanutkun_5',
			width: 84,
			height: 200,
			halfWidth: 42,
			halfHeight: 100,
			isTarget: true,
			scoreRate: 1.2,
		},
		'Ponpoko_1': {
			name: 'Ponpoko_1',
			width: 129,
			height: 200,
			halfWidth: 64.5,
			halfHeight: 100,
			isTarget: false,
			scoreRate: 4,
		},
		'Ponpoko_2': {
			name: 'Ponpoko_2',
			width: 200,
			height: 200,
			halfWidth: 100,
			halfHeight: 100,
			isTarget: false,
			scoreRate: 3,
		},
	};
};
