BasicGame.Boot.prototype.genStageInfo=function(){
	return {
		1:{name:'Level 1',targetScore:0,closed:!1,
			noteKeys:['Banana_1','Banana_2'],
			obstacleKeys:['Banana_3'],
			loopNotesTime:400,loopObstaclesTime:1E3,playerMoveSpeed:.3,
			playerLife:5,gravityRangeMin:100,gravityRangeMax:200,
		},
		2:{name:'Level 2',targetScore:0,closed:!1,
			noteKeys:['Banana_1','Banana_2','Food_1'],
			obstacleKeys:['Banana_3'],
			loopNotesTime:400,loopObstaclesTime:800,playerMoveSpeed:.3,
			playerLife:4,gravityRangeMin:100,gravityRangeMax:300,
		},
		3:{name:'Level 3',targetScore:0,closed:!1,
			noteKeys:['Banana_1','Banana_2','Food_1','Food_2'],
			obstacleKeys:['Banana_3','Obstacle_1'],
			loopNotesTime:300,loopObstaclesTime:800,playerMoveSpeed:.3,
			playerLife:3,gravityRangeMin:100,gravityRangeMax:400,
		},
		4:{name:'Level 4',targetScore:0,closed:!1,
			noteKeys:['Banana_1','Banana_2','Food_1','Food_2','Food_3'],
			obstacleKeys:['Banana_3','Obstacle_1','Obstacle_2'],
			loopNotesTime:200,loopObstaclesTime:500,playerMoveSpeed:.4,
			playerLife:2,gravityRangeMin:100,gravityRangeMax:500,
		},
		5:{name:'タイムアタック60',targetScore:0,closed:!1,
			noteKeys:['Banana_1','Banana_2'],
			obstacleKeys:['Banana_3'],
			loopNotesTime:200,loopObstaclesTime:500,playerMoveSpeed:.4,
			playerLife:999999,gravityRangeMin:100,gravityRangeMax:500,
		},
		6:{name:'タイムアタック120',targetScore:0,closed:!1,
			noteKeys:['Banana_1','Banana_2','Food_1','Food_2','Food_3','Food_4','Food_5','Food_6'],
			obstacleKeys:['Banana_3','Obstacle_1','Obstacle_2'],
			loopNotesTime:200,loopObstaclesTime:500,playerMoveSpeed:.4,
			playerLife:999999,gravityRangeMin:100,gravityRangeMax:500,
		},
		7:{name:'サドンデススコア',targetScore:0,closed:!1,
			noteKeys:['Banana_1','Banana_2','Food_1','Food_2','Food_3','Food_4','Food_5'],
			obstacleKeys:['Banana_3','Obstacle_1','Obstacle_2'],
			loopNotesTime:200,loopObstaclesTime:500,playerMoveSpeed:.7,
			playerLife:1,gravityRangeMin:100,gravityRangeMax:600,
		},
		8:{name:'サドンデススコア改',targetScore:0,closed:!0,
			noteKeys:['Banana_1','Banana_2','Food_1','Food_2','Food_3','Food_4','Food_5','Food_6'],
			obstacleKeys:['Banana_3','Obstacle_1','Obstacle_2'],
			loopNotesTime:400,loopObstaclesTime:200,playerMoveSpeed:.8,
			playerLife:1,gravityRangeMin:100,gravityRangeMax:1000,
		},
	};
};
BasicGame.Boot.prototype.genWords=function(){
	return {
		jp:{
			Start:'スタート',
			OtherGames:'他のゲーム',
			Back:'もどる',
			Again:'もういちど',
			HowTo:'',
			Tweet:'結果をツイート',
			TweetTtl:'『'+BasicGame.GAME_TITLE+'』で遊んだよ！',
			Clear:'',
		},
		en:{},//TODO
	};
};