BasicGame.Boot.prototype.genCharInfo=function(){
	return {
		1:{name:'森中花咲',playerMoveSpeed:1,
			delayLoopObstaclesTime:0,
			scoreRate:10,minusScoreRate:1,
			closed:!1,playerImg:'Kazaki_1',introImg:'Kazaki_1',
		},
		2:{name:'森中花咲',playerMoveSpeed:.8,
			delayLoopObstaclesTime:100,
			scoreRate:8,minusScoreRate:.8,
			closed:!0,playerImg:'Kazaki_1',introImg:'Kazaki_1',
		},
		3:{name:'森中花咲',playerMoveSpeed:1.2,
			delayLoopObstaclesTime:0,
			scoreRate:12,minusScoreRate:1.2,
			closed:!0,playerImg:'Kazaki_1',introImg:'Kazaki_1',
		},
		4:{name:'森中花咲',playerMoveSpeed:2,
			delayLoopObstaclesTime:-100,
			scoreRate:20,minusScoreRate:2,
			closed:!0,playerImg:'Kazaki_1',introImg:'Kazaki_1',
		},
	};
};
BasicGame.Boot.prototype.genStageInfo=function(){
	return {
		1:{name:'Level 1',closed:!1,mode:1,
			noteKeys:['Banana_1','Banana_2'],
			obstacleKeys:['Banana_3'],
			loopNotesTime:400,loopObstaclesTime:1E3,playerMoveSpeed:.3,
			playerLife:5,gravityRangeMin:100,gravityRangeMax:200,
			targetScore:10000,scoreRate:1,
			timeAttackLeftTime:null,
		},
		2:{name:'Level 2',closed:!1,mode:1,
			noteKeys:['Banana_1','Banana_2','Food_1'],
			obstacleKeys:['Banana_3'],
			loopNotesTime:400,loopObstaclesTime:800,playerMoveSpeed:.3,
			playerLife:4,gravityRangeMin:100,gravityRangeMax:300,
			targetScore:50000,scoreRate:2,
			timeAttackLeftTime:null,
		},
		3:{name:'Level 3',closed:!1,mode:1,
			noteKeys:['Banana_1','Banana_2','Food_1','Food_2'],
			obstacleKeys:['Banana_3','Obstacle_1'],
			loopNotesTime:300,loopObstaclesTime:700,playerMoveSpeed:.3,
			playerLife:3,gravityRangeMin:100,gravityRangeMax:400,
			targetScore:100000,scoreRate:3,
			timeAttackLeftTime:null,
		},
		4:{name:'Level 4',closed:!1,mode:1,
			noteKeys:['Banana_1','Banana_2','Food_1','Food_2','Food_3'],
			obstacleKeys:['Banana_3','Obstacle_1','Obstacle_2'],
			loopNotesTime:200,loopObstaclesTime:500,playerMoveSpeed:.4,
			playerLife:2,gravityRangeMin:100,gravityRangeMax:500,
			targetScore:500000,scoreRate:4,
			timeAttackLeftTime:null,
		},
		5:{name:'タイムアタック60',closed:!1,mode:2,
			noteKeys:['Banana_1','Banana_2'],
			obstacleKeys:['Banana_3'],
			loopNotesTime:200,loopObstaclesTime:500,playerMoveSpeed:.4,
			playerLife:null,gravityRangeMin:100,gravityRangeMax:500,
			targetScore:null,scoreRate:10,
			timeAttackLeftTime:60,
		},
		6:{name:'タイムアタック120',closed:!1,mode:2,
			noteKeys:['Banana_1','Banana_2','Food_1','Food_2','Food_3','Food_4','Food_5','Food_6'],
			obstacleKeys:['Banana_3','Obstacle_1','Obstacle_2'],
			loopNotesTime:100,loopObstaclesTime:400,playerMoveSpeed:.4,
			playerLife:null,gravityRangeMin:100,gravityRangeMax:700,
			targetScore:null,scoreRate:10,
			timeAttackLeftTime:120,
		},
		7:{name:'サドンデススコア',closed:!1,mode:3,
			noteKeys:['Banana_1','Banana_2','Food_1','Food_2','Food_3','Food_4','Food_5'],
			obstacleKeys:['Banana_3','Obstacle_1','Obstacle_2'],
			loopNotesTime:200,loopObstaclesTime:500,playerMoveSpeed:.7,
			playerLife:1,gravityRangeMin:100,gravityRangeMax:600,
			targetScore:null,scoreRate:10,
			timeAttackLeftTime:null,
		},
		8:{name:'サドンデススコア改',closed:!0,mode:3,
			noteKeys:['Banana_1','Banana_2','Food_1','Food_2','Food_3','Food_4','Food_5','Food_6'],
			obstacleKeys:['Banana_3','Obstacle_1','Obstacle_2'],
			loopNotesTime:400,loopObstaclesTime:200,playerMoveSpeed:.8,
			playerLife:1,gravityRangeMin:500,gravityRangeMax:1000,
			targetScore:null,scoreRate:20,
			timeAttackLeftTime:null,
		},
	};
};
BasicGame.Boot.prototype.genWords=function(){
	return {
		jp:{
			Start:'スタート',
			Back:'もどる',
			// TODO バナナなど -> アイテム？良品？  // 傷んだバナナなど->???
			// TODO アイテムが悪いとハートがなくなる?
			HowTo_1:'目標のスコアを目指して\nバナナなどを取ろう！\n右のハートがなくなったら\nゲームオーバー！\n高レベルクリアで\n隠しキャラがオープン！？',
			HowTo_2:'制限時間まで\nバナナなどを取って\nハイスコアを目指せ！\n傷んだバナナなどは\nスコアが減るよ！\nどこまでスコアを伸ばせるか…\nTwitterのみんなと競争だ！',
			HowTo_3:'命の限り\nバナナなどを取り続けよう！\nどこまでスコアを伸ばせるか…\nTwitterのみんなと競争だ！\n高スコアで さらなる\n隠しステージが…！',
			CurScore:'スコア: ',
			TargetScore:'目標: ',
			TimeAttack:'制限時間: ',
			GameOver:'ゲームオーバー',
			Clear:'クリア！',
			Timeout:'終了！',
			Result:'結果',
			Again:'もういちど',
			OtherGames:'他のゲーム',
			Tweet:'結果をツイート',
			TweetTtl:'『'+BasicGame.GAME_TITLE+'』で遊んだよ！',
			TweetHT:'かざゲー',
			TweetResChar:'キャラ: ',
			TweetResStg:'ステージ: ',
			TweetResScore:'スコア: ',
			NextStg:'次のレベルへ',
			OpenNewStg:'新ステージ\nオープン！',
			OpenNewChar:'新キャラ\nオープン！',
			SelectStg:'ステージを選んでね',
			SelectChar:'キャラを選んでね',
		},
		en:{},//TODO
	};
};