BasicGame.Boot.prototype.conf = function () {
	var totalCount = 14;
	return {
		GamesInfo:{
			1001: {
				id: 1001,
				title: '秒当てゲーム',
				url: 'https://238g.github.io/hitten/',
				slideImg: 'Hitten_1',
				slideImgUrl: './images/238Games/Hitten_1.png',
				order: totalCount-1,
				textColor: '#000000',
				bgColor: '#fbf6d5',
			},
			1002: {
				id: 1002,
				title: 'レッツ・あん肝！',
				url: 'https://238g.github.io/Parace/ankimo_drrrr.html',
				slideImg: 'player',
				slideImgUrl: './images/ankimo_drrrr/player.png',
				order: totalCount-2,
				textColor: '#e68946',
				bgColor: '#fbf6d5',
			},
			1003: {
				id: 1003,
				title: 'シロラン',
				url: 'https://238g.github.io/Parace/sirorun.html',
				slideImg: 'Sirorun_1',
				slideImgUrl: './images/238Games/Sirorun_1.png',
				order: totalCount-3,
				textColor: '#5fa0dc',
				bgColor: '#ffffff',
			},
			1004: {
				id: 1004,
				title: '燃やせ！エルフの森！',
				url: 'https://238g.github.io/Parace/eff.html',
				slideImg: 'elu_1',
				slideImgUrl: './images/eff/elu_1.png',
				order: totalCount-4,
				textColor: '#dd5a52',
				bgColor: '#48984b',
			},
			1005: {
				id: 1005,
				title: 'テンちょう🚫バスたーず',
				url: 'https://238g.github.io/Parace/cafenozombiko.html',
				slideImg: 'Zombiko_1',
				slideImgUrl: './images/cafenozombiko/Zombiko_1.png',
				order: totalCount-5,
				textColor: '#b8860b',
				bgColor: '#a0522d',
			},
			1006: {
				id: 1006,
				title: '天魔機忍ストーンズverG',
				url: 'https://238g.github.io/Parace/TenMaKiNinVerG.html',
				slideImg: 'CharStones',
				slideImgUrl: 'images/238Games/TenMaKiNinVerG.png',
				order: totalCount-6,
				textColor: '#000000',
				bgColor: '#6298ff',
			},
			1007: {
				id: 1007,
				title: 'アズリム節',
				url: 'https://238g.github.io/Parace/AzlimBushi.html',
				slideImg: 'Azlim_2',
				slideImgUrl: './images/AzlimBushi/Azlim_2.png',
				order: totalCount-7,
				textColor: '#9a53eb',
				bgColor: '#d494fd',
			},
			1008: {
				id: 1008,
				title: '虚空の果てに',
				url: 'https://238g.github.io/Parace/rei_Toya_rei.html',
				slideImg: 'ToyaFace_1',
				slideImgUrl: './images/rei_Toya_rei/ToyaFace_1.png',
				order: totalCount-8,
				textColor: '#917492',
				bgColor: '#a1a4ad',
			},
			1009: {
				id: 1009,
				title: 'まりちゃんばりん',
				url: 'https://238g.github.io/Parace/kashikomari.html',
				slideImg: 'Kashikomari_1',
				slideImgUrl: './images/kashikomari/Kashikomari_1.png',
				order: totalCount-9,
				textColor: '#eaad18',
				bgColor: '#fffd3a',
			},
			1010: {
				id: 1010,
				title: '田中ヒメ中華街',
				url: 'https://238g.github.io/Parace/HimeTanaka.html',
				slideImg: 'HimeTanaka_1',
				slideImgUrl: './images/238Games/HimeTanaka_1.png',
				order: totalCount-10,
				textColor: '#e30c4f',
				bgColor: '#fba4d1',
			},
			1011: {
				id: 1011,
				title: 'アリス・トラーツ',
				url: 'https://238g.github.io/Parace/AliceMononobe.html',
				slideImg: 'AliceMononobe_1',
				slideImgUrl: './images/238Games/AliceMononobe_1.png',
				order: totalCount-11,
				textColor: '#89beff',
				bgColor: '#fde5b1',
			},
			1012: {
				id: 1012,
				title: 'ちあは魔法少女',
				url: 'https://238g.github.io/Parace/tiatia.html',
				slideImg: 'Tiatia_1',
				slideImgUrl: './images/238Games/Tiatia_1.png',
				order: totalCount-12,
				textColor: '#ff94fc',
				bgColor: '#9dddef',
			},
			1013: {
				id: 1013,
				title: 'ミラアカゲーム(虹)',
				url: 'https://238g.github.io/Parace/MiraAka.html',
				slideImg: 'TitleBg',
				slideImgUrl: 'images/MiraAka/TitleBg.jpg',
				order: totalCount-13,
				textColor: '#2ca0eb',
				bgColor: '#52deff',
			},
			1014: {
				id: 1014,
				title: 'ぶちとば!💥🚀ケリンさん',
				url: 'https://238g.github.io/Parace/Kerin.html',
				slideImg: 'Kerin_1',
				slideImgUrl: 'images/238Games/Kerin_1.jpg',
				order: totalCount-14,
				textColor: '#56665b',
				bgColor: '#dfc6a7',
			},
			/*
			1000: {
				id: 1000,
				title: 'title5',
				url: '55555abcdefg',
				slideImg: 'BeefBowl',
				slideImgUrl: './images/AzlimBushi/BeefBowl.png',
				order: 1,
				// color? sub,text
				// list thumbnail?
			},
			*/
		},
	};
};