function genGamesInfo(){
	return {GamesInfo:{
			1001:{id:1001,title:'秒当てゲーム',url:'https://238g.github.io/hitten/index.html',
				tColor:'#000000',mColor:'#fbf6d5',
				tc:null,imgA:'images/238Games/Hitten_1.png',imgB:'https://238g.github.io/hitten/images/favicons/sunny-side-up-32-293206.png',
				caption:'',
				release:'2018/2/12',
			},
			1002:{id:1002,title:'レッツ・あん肝！',url:GI2A('ankimo_drrrr'),
				tColor:'#e68946',mColor:'#fbf6d5',
				tc:GI2B('ankimo_drrrr'),imgA:GI2C('ankimo_drrrr'),imgB:GI2D('ankimo_drrrr'),
				caption:'あん肝の二次創作ゲーム！あん肝はときのそらちゃんの動画に出てくるクマだよ！動物たちを避けて高得点を狙おう！',
				release:'2018/2/18',
			},
			1003:{id:1003,title:'シロラン',url:GI2A('sirorun'),
				tColor:'#5fa0dc',mColor:'#ffffff',
				tc:GI2B('sirorun'),imgA:GI2C('sirorun'),imgB:GI2D('sirorun'),
				caption:'電脳少女シロちゃんの二次創作ゲームです！シロちゃんをジャンプさせて、ばあちゃるをひたすら避けるんだ！フェイントウビバに気をつけろ！',
				release:'2018/3/2',
			},
			1004:{id:1004,title:'燃やせ！エルフの森！',url:GI2A('eff'),
				tColor:'#dd5a52',mColor:'#48984b',
				tc:GI2B('eff'),imgA:GI2C('eff'),imgB:GI2D('eff'),
				caption:'にじさんじエルフのえるちゃんの二次創作ゲーム…？焼森は…スポーツ！みんなで焼森してね🔥🔥🌲🌲🔥🔥_(-ω- ´ _)⌒)_',
				release:'2018/3/6',
			},
			1005:{id:1005,title:'テンちょう🚫バスたーず',url:GI2A('cafenozombiko'),
				tColor:'#b8860b',mColor:'#a0522d',
				tc:GI2B('cafenozombiko'),imgA:GI2C('cafenozombiko'),imgB:GI2D('cafenozombiko'),
				caption:'カフェ野ゾンビ子の二次創作ゲームです！ミニゾンビ化した店長をたくさん倒せ✨✨人間は敵だぞ？！',
				release:'2018/3/10',
			},
			1006:{id:1006,title:'天魔機忍ストーンズverG',url:GI2A('TenMaKiNinVerG'),
				tColor: '#000000',mColor: '#6298ff',
				tc:GI2B('TenMaKiNinVerG'),imgA:GI2C('TenMaKiNinVerG'),imgB:GI2D('TenMaKiNinVerG'),
				caption:'天魔機忍verGの二次創作パズルゲームです！好きなキャラクターで高得点を目指そう！',
				release:'2018/3/17',
			},
			1007:{id:1007,title:'アズリム節',url:GI2A('AzlimBushi'),
				tColor:'#9a53eb',mColor:'#d494fd',
				tc:GI2B('AzlimBushi'),imgA:GI2C('AzlimBushi'),imgB:GI2D('AzlimBushi'),
				caption:'アズマリムちゃんの二次創作ゲームです！たくさんの魚を捕まえて高得点を目指せ！センパイたち～ぃ、やってくれよ！',
				release:'2018/3/24',
			},
			1008:{id:1008,title:'虚空の果てに',url:GI2A('rei_Toya_rei'),
				tColor:'#917492',mColor:'#a1a4ad',
				tc:GI2B('rei_Toya_rei'),imgA:GI2C('rei_Toya_rei'),imgB:GI2D('rei_Toya_rei'),
				caption:'にじさんじ剣持刀也くんの二次創作ゲームです！力也ゲーム！タイトル画面で存分に遊んで欲しい…',
				release:'2018/3/28',
			},
			1009:{id:1009,title:'まりちゃんばりん',url:GI2A('kashikomari'),
				tColor:'#eaad18',mColor:'#fffd3a',
				tc:GI2B('kashikomari'),imgA:GI2C('kashikomari'),imgB:GI2D('kashikomari'),
				caption:'かしこまりちゃんの二次創作音楽ゲームです！YouTubeの動画にのせてリズムパンディを刻め！😐😐😐出せるかな？Sランク！',
				release:'2018/4/1',
			},
			1010:{id:1010,title:'田中ヒメ中華街',url:GI2A('HimeTanaka'),
				tColor:'#e30c4f',mColor:'#fba4d1',
				tc:GI2B('HimeTanaka'),imgA:GI2C('HimeTanaka'),imgB:GI2D('HimeTanaka'),
				caption:'田中ヒメちゃんの二次創作ゲームです！肉まんをヒメに送り届けろ！さすれば君も今日から田中ァ！',
				release:'2018/4/13',
			},
			1011:{id:1011,title:'アリス・トラーツ',url:GI2A('AliceMononobe'),
				tColor:'#89beff',mColor:'#fde5b1',
				tc:GI2B('AliceMononobe'),imgA:GI2C('AliceMononobe'),imgB:GI2D('AliceMononobe'),
				caption:'にじさんじ物述有栖ちゃんの二次創作トランプゲームです！トランプとダーツを組み合わせた新感覚ゲーム！にじさんじ2期生全員のデザイントランプを使っているよ！',
				release:'2018/4/21',
			},
			1012:{id:1012,title:'ちあは魔法少女',url:GI2A('tiatia'),
				tColor:'#ff94fc',mColor:'#9dddef',
				tc:GI2B('tiatia'),imgA:GI2C('tiatia'),imgB:GI2D('tiatia'),
				caption:'魔法少女ちあちゃんの二次創作シューティングゲームです！イヌージョンがボスとして登場？！あなたはクリアまでたどりつけるか…？！',
				release:'2018/4/29',
			},
			1013:{id:1013,title:'ミラアカゲーム(虹)',url:GI2A('MiraAka'),
				tColor:'#2ca0eb',mColor:'#52deff',
				tc:GI2B('MiraAka'),imgA:GI2C('MiraAka'),imgB:GI2D('MiraAka'),
				caption:'ミラアカゲームの二次創作ゲームです！４問間違えると罰ゲームが決定しちゃうかも？！みんなで遊んで盛り上がろう！',
				release:'2018/5/12',
			},
			1014:{id:1014,title:'ぶちとば!💥🚀ケリンさん',url:GI2A('Kerin'),
				tColor:'#56665b',mColor:'#dfc6a7',
				tc:GI2B('Kerin'),imgA:GI2C('Kerin'),imgB:GI2D('Kerin'),
				caption:'ケリンさんの二次創作ゲームです！春日部つくしちゃんやにじさんじを避けて目的地へ向かおう！ぶちとば！💥🚀',
				release:'2018/5/16',
			},
			1015:{id:1015,title:'脱衣ちーちゃん',url:GI2A('ChihiroGame'),
				tColor:'#7169d9',mColor:'#a9aee5',
				tc:GI2B('ChihiroGame'),imgA:GI2C('ChihiroGame'),imgB:GI2D('ChihiroGame'),
				caption:'にじさんじ勇気ちひろちゃんの二次創作ブロック崩しゲームです！ちーちゃんが色んな人を脱がしちゃう…？(笑)脱がした画像もゲット…！？',
				release:'2018/5/20',
			},
			1016:{id:1016,title:'ピーナッツ忍者',url:GI2A('PeanutNinja'),
				tColor:'#a17b63',mColor:'#fef106',
				tc:GI2B('PeanutNinja'),imgA:GI2C('PeanutNinja'),imgB:GI2D('PeanutNinja'),
				caption:'甲賀流忍者ぽんぽことピーナッツくんの二次創作ゲームです。飛んでくるピーナッツくんを切って切って切りまくれ！ぽんぽこは切らないでね！',
				release:'2018/5/26',
			},
			1017:{id:1017,title:'グンッマー葵',url:GI2A('AoiGame'),
				tColor:'#106ab7',mColor:'#6aa3d9',
				tc:GI2B('AoiGame'),imgA:GI2C('AoiGame'),imgB:GI2D('AoiGame'),
				caption:'富士葵ちゃんの二次創作ゲームです。キクノジョーをグンッすべく、葵ちゃんが奮闘します！簡単なタッチ操作で遊べるので是非遊んでくださいね！',
				release:'2018/6/4',
			},
			1018:{id:1018,title:'織田だだだだだだだだ',url:GI2A('Odadadadadadadadadada'),
				tColor:'#ff549c',mColor:'#cbdf9c',
				tc:GI2B('Oda'),imgA:GI2C('Oda'),imgB:GI2D('Oda'),
				caption:'織田信姫とおだのぶの二次創作ゲームです！用意された50レベルもの試練を乗り越えろ！さぁ、ひたすら織田軍を刺すのです！',
				release:'2018/6/10',
			},
			1019:{id:1019,title:'スナイパーひなた',url:GI2A('Nekomiya'),
				tColor:'#f8978f',mColor:'#ff7f26',
				tc:GI2B('Nekomiya'),imgA:GI2C('Nekomiya'),imgB:GI2D('Nekomiya'),
				caption:'猫宮ひなたちゃんの二次創作ゲームです。スナイパーとなってクレーと呼ばれるお皿をどれだけ壊せることができるのか…あなたのエイム力が試される…！',
				release:'2018/6/17',
			},
			1020:{id:1020,title:'あさひさんいじり',url:GI2A('FOckingGlasses'),
				tColor:'#503110',mColor:'#aee9f3',
				tc:GI2B('FOckingGlasses'),imgA:GI2C('FOckingGlasses'),imgB:GI2D('FOckingGlasses'),
				caption:'クソメガネことあさひくんの二次創作ゲームです。タッチして存分にいじってあげてください！いじればいじるほどメガネが割れます（）',
				release:'2018/6/28',
			},
			1021:{id:1021,title:'おめシスコマンダーズ',url:GI2A('OmesisCommanders'),
				tColor:'#d16769',mColor:'#668af6',
				tc:GI2B('OmesisCommanders'),imgA:GI2C('OmesisCommanders'),imgB:GI2D('OmesisCommanders'),
				caption:'おめがシスターズによって制作されたVtuberFightersの二次創作ゲームです！コマンドを覚えて相手を攻撃しよう！あなたの記憶力はどのくらい…！？',
				release:'2018/7/04',
			},
			1022:{id:1022,title:'トラック女神',url:GI2A('TruckGoddess'),
				tColor:'#28ceff',mColor:'#c8f7f4',
				tc:GI2B('TruckGoddess'),imgA:GI2C('TruckGoddess'),imgB:GI2D('TruckGoddess'),
				caption:'にじさんじモイラ様におけるトラック女神の二次創作ゲームです！あのトラック女神を忠実に再現！？',
				release:'2018/7/15',
			},
			1023:{id:1023,title:'MitoDanceRevolution',url:GI2A('MitoDanceRevolution'),
				tColor:'#ec74af',mColor:'#012c9e',
				tc:GI2B('MitoDanceRevolution'),imgA:GI2C('MitoDanceRevolution'),imgB:GI2D('MitoDanceRevolution'),
				caption:'例のあのゲームが月ノ美兎バージョンになって登場！素晴らしい踊りを堪能せよ！',
				release:'2018/7/22',
			},
			1024:{id:1024,title:'ラキぴょこぴょこ',url:GI2A('Laki'),
				tColor:'#7ae66f',mColor:'#f6d48f',
				tc:GI2B('Laki'),imgA:GI2C('Laki'),imgB:GI2D('Laki'),
				caption:'きらっきー☆ヾ(o\'▽\'o)ゝ虹河ラキちゃんの二次創作ゲームです！ぴょこぴょこラキちゃんをジャンプさせよう！',
				release:'2018/7/30',
			},
			1025:{id:1025,title:'もちもちフィッシング',url:GI2A('MMFishing'),
				tColor:'#a981af',mColor:'#e5c6cd',
				tc:GI2B('MM_Fishing'),imgA:GI2C('MM_Fishing'),imgB:GI2D('MM_Fishing'),
				caption:'にじさんじ宇志海いちごちゃんの二次創作ゲームです！生放送で話題になったあの釣りゲームを再現！',
				release:'2018/8/05',
			},
			1026:{id:1026,title:'シズザレン工場',url:GI2A('Shizuzaren'),
				tColor:'#4f5790',mColor:'#d0c7cc',
				tc:GI2B('Shizuzaren'),imgA:GI2C('Shizuzaren'),imgB:GI2D('Shizuzaren'),
				caption:'にじさんじギルザレンⅢ世と静凛さんの二次創作ゲームです！腹筋をポコポコ取る気持ちよさがグッド！絵師の四季丸さんのギルザレンしずりん腹筋ネタを元に制作しています！',
				release:'2018/8/17',
			},
			1027:{id:1027,title:'ドーラ様の度胸試し',url:GI2A('Dora'),
				tColor:'#c42021',mColor:'#ffa424',
				tc:GI2B('Dora'),imgA:GI2C('Dora'),imgB:GI2D('Dora'),
				caption:'にじさんじSEEDsドーラ様の二次創作ゲームです！ドーラ様と一緒に度胸試しにチャレンジ！花畑チャイカ殿も火炎瓶と共に登場！？',
				release:'2018/8/24',
			},
			1028:{id:1028,title:'森中花咲のバナ〜ナFight',url:GI2A('Kazaki'),
				tColor:'#64c100',mColor:'#cbdc7d',
				tc:GI2B('Kazaki'),imgA:GI2C('Kazaki'),imgB:GI2D('Kazaki'),
				caption:'にじさんじ森中花咲ちゃんの二次創作ゲーム！木から降ってくるバナナやいちごをキャッチしよう！生放送でお馴染みのキャラクターはキャッチしたら大変なことに！？',
				release:'2018/9/1',
			},
			1029:{id:1029,title:'upd8神経衰弱',url:GI2A('upd8Game'),
				tColor:'#6e6d6b',mColor:'#ffffff',
				tc:GI2B('upd8Game'),imgA:GI2C('upd8Game'),imgB:GI2D('upd8Game'),
				caption:'upd8の二次創作ゲームです！総勢41組を神経衰弱で覚えよう！',
				release:'2018/9/8',
			},
			1030:{id:1030,title:'Tofu On Fire',url:GI2A('mei'),
				tColor:'#f62018',mColor:'#cbd7ea',
				tc:GI2B('mei'),imgA:GI2C('mei'),imgB:GI2D('mei'),
				caption:'upd8小山内めいちゃんの二次創作ゲームです！豆腐を燃やして📛をゲットしよう！そう！これこそTofuOnFire！ミソシタも友情出演！？',
				release:'2018/9/16',
			},
		},
	};
};
var __baseUrl=__ENV=='prod'?'https://238g.github.io/Parace/':'./';
function GI2A(n){return __baseUrl+n+'.html'}
function GI2B(n){return __baseUrl+'images/'+n+'/TwitterCard.jpg'}
function GI2C(n){return __baseUrl+'images/'+n+'/favicons/ms-icon-310x310.png'}
function GI2D(n){return __baseUrl+'images/'+n+'/favicons/favicon-32x32.png'}
