BasicGame.Boot.prototype.genGamesInfo = function () {
	var totalCount = 17;
	return {
		GamesInfo:{
			1001: {
				id: 1001,
				title: '秒当てゲーム',
				url: 'https://238g.github.io/hitten/',
				slideImg: 'Hitten_1',
				slideImgUrl: 'images/238Games/Hitten_1.png',
				order: totalCount-1,
				textColor: '#000000',
				bgColor: '#fbf6d5',
				scale: .4,
			},
			1002: {
				id: 1002,
				title: 'レッツ・あん肝！',
				url: 'https://238g.github.io/Parace/ankimo_drrrr.html',
				slideImg: 'player',
				slideImgUrl: 'images/ankimo_drrrr/player.png',
				order: totalCount-2,
				textColor: '#e68946',
				bgColor: '#fbf6d5',
				scale: .4,
			},
			1003: {
				id: 1003,
				title: 'シロラン',
				url: 'https://238g.github.io/Parace/sirorun.html',
				slideImg: 'Sirorun_1',
				slideImgUrl: 'images/238Games/Sirorun_1.png',
				order: totalCount-3,
				textColor: '#5fa0dc',
				bgColor: '#ffffff',
				scale: .4,
			},
			1004: {
				id: 1004,
				title: '燃やせ！エルフの森！',
				url: 'https://238g.github.io/Parace/eff.html',
				slideImg: 'elu_1',
				slideImgUrl: 'images/eff/elu_1.png',
				order: totalCount-4,
				textColor: '#dd5a52',
				bgColor: '#48984b',
				scale: .4,
			},
			1005: {
				id: 1005,
				title: 'テンちょう🚫バスたーず',
				url: 'https://238g.github.io/Parace/cafenozombiko.html',
				slideImg: 'Zombiko_1',
				slideImgUrl: 'images/cafenozombiko/Zombiko_1.png',
				order: totalCount-5,
				textColor: '#b8860b',
				bgColor: '#a0522d',
				scale: .4,
			},
			1006: {
				id: 1006,
				title: '天魔機忍ストーンズverG',
				url: 'https://238g.github.io/Parace/TenMaKiNinVerG.html',
				slideImg: 'CharStones',
				slideImgUrl: 'images/238Games/TenMaKiNinVerG.png',
				order: totalCount-6,
				textColor: '#000000',
				bgColor: '#6298ff',
				scale: .4,
			},
			1007: {
				id: 1007,
				title: 'アズリム節',
				url: 'https://238g.github.io/Parace/AzlimBushi.html',
				slideImg: 'Azlim_2',
				slideImgUrl: 'images/AzlimBushi/Azlim_2.png',
				order: totalCount-7,
				textColor: '#9a53eb',
				bgColor: '#d494fd',
				scale: .4,
			},
			1008: {
				id: 1008,
				title: '虚空の果てに',
				url: 'https://238g.github.io/Parace/rei_Toya_rei.html',
				slideImg: 'ToyaFace_1',
				slideImgUrl: 'images/rei_Toya_rei/ToyaFace_1.png',
				order: totalCount-8,
				textColor: '#917492',
				bgColor: '#a1a4ad',
				scale: .4,
			},
			1009: {
				id: 1009,
				title: 'まりちゃんばりん',
				url: 'https://238g.github.io/Parace/kashikomari.html',
				slideImg: 'Kashikomari_1',
				slideImgUrl: 'images/kashikomari/Kashikomari_1.png',
				order: totalCount-9,
				textColor: '#eaad18',
				bgColor: '#fffd3a',
				scale: .4,
			},
			1010: {
				id: 1010,
				title: '田中ヒメ中華街',
				url: 'https://238g.github.io/Parace/HimeTanaka.html',
				slideImg: 'HimeTanaka_1',
				slideImgUrl: 'images/238Games/HimeTanaka_1.png',
				order: totalCount-10,
				textColor: '#e30c4f',
				bgColor: '#fba4d1',
				scale: .4,
			},
			1011: {
				id: 1011,
				title: 'アリス・トラーツ',
				url: 'https://238g.github.io/Parace/AliceMononobe.html',
				slideImg: 'AliceMononobe_1',
				slideImgUrl: 'images/238Games/AliceMononobe_1.png',
				order: totalCount-11,
				textColor: '#89beff',
				bgColor: '#fde5b1',
				scale: .4,
			},
			1012: {
				id: 1012,
				title: 'ちあは魔法少女',
				url: 'https://238g.github.io/Parace/tiatia.html',
				slideImg: 'Tiatia_1',
				slideImgUrl: 'images/238Games/Tiatia_1.png',
				order: totalCount-12,
				textColor: '#ff94fc',
				bgColor: '#9dddef',
				scale: .4,
			},
			1013: {
				id: 1013,
				title: 'ミラアカゲーム(虹)',
				url: 'https://238g.github.io/Parace/MiraAka.html',
				slideImg: 'TitleBg',
				slideImgUrl: 'images/MiraAka/TitleBg.jpg',
				order: totalCount-13,
				textColor: '#2ca0eb',
				bgColor: '#52deff',
				scale: .4,
			},
			1014: {
				id: 1014,
				title: 'ぶちとば!💥🚀ケリンさん',
				url: 'https://238g.github.io/Parace/Kerin.html',
				slideImg: 'Kerin_1',
				slideImgUrl: 'images/238Games/Kerin_1.jpg',
				order: totalCount-14,
				textColor: '#56665b',
				bgColor: '#dfc6a7',
				scale: .4,
			},
			1015: {
				id: 1015,
				title: '脱衣ちーちゃん',
				url: 'https://238g.github.io/Parace/ChihiroGame.html',
				slideImg: 'Chihiro_1',
				slideImgUrl: 'images/ChihiroGame/Chihiro_1.png',
				order: totalCount-15,
				textColor: '#7169d9',
				bgColor: '#a9aee5',
				scale: .4,
			},
			1016: {
				id: 1016,
				title: 'ピーナッツ忍者',
				url: 'https://238g.github.io/Parace/PeanutNinja.html',
				slideImg: 'Peanutkun_Face',
				slideImgUrl: 'images/PeanutNinja/Peanutkun_Face.png',
				order: totalCount-16,
				textColor: '#a17b63',
				bgColor: '#fef106',
				scale: 1,
			},
			1017: {
				id: 1017,
				title: 'グンッマー葵',
				url: 'https://238g.github.io/Parace/AoiGame.html',
				slideImg: 'Aoi_1',
				slideImgUrl: 'images/AoiGame/Aoi_1.png',
				order: totalCount-17,
				textColor: '#106ab7',
				bgColor: '#6aa3d9',
				scale: 1,
			},
		},
	};
};