BasicGame.Boot.prototype.genCharInfo = function () {
	return {
		'Char_1': {
			name: 'がっくん',
			DLFile: 'がっくんのビキニ.png',
			key: 'Char_1',
			imgPath: './images/ChihiroGame/Gaku_Before.jpg',
			backKey: 'Char_1_b',
			bgImgPath: './images/ChihiroGame/Gaku_After.jpg',
			panelKey: 'Char_1_All',
			width: 70,
			height: 40,
			holizontal: 10,
			vertical: 25,
			imgWidth: 700,
			imgHeight: 1000,
			clearCount: 8,
			frameX: 0,
			frameY: 200,
			offer: null,
			ballStandardSpeedY: -400,
			maxVelocityY: 900,
		},
		'Char_2': {
			name: 'ハジメお兄ちゃん',
			DLFile: 'ハジメお兄ちゃんのビキニ.png',
			key: 'Char_2',
			imgPath: './images/ChihiroGame/Hajime_Before.jpg',
			backKey: 'Char_2_b',
			bgImgPath: './images/ChihiroGame/Hajime_After.jpg',
			panelKey: 'Char_2_All',
			width: 70,
			height: 40,
			holizontal: 10,
			vertical: 25,
			imgWidth: 700,
			imgHeight: 1000,
			clearCount: 8,
			frameX: 0,
			frameY: 200,
			offer: null,
			ballStandardSpeedY: -400,
			maxVelocityY: 1100,
		},
		'Char_3': {
			name: 'ちーちゃん',
			DLFile: 'ちーちゃんのビキニ.png',
			key: 'Char_3',
			imgPath: './images/ChihiroGame/Chihiro_Before.jpg',
			backKey: 'Char_3_b',
			bgImgPath: './images/ChihiroGame/Chihiro_After.jpg',
			panelKey: 'Char_3_All',
			width: 50,
			height: 35,
			holizontal: 14,
			vertical: 20,
			imgWidth: 700,
			imgHeight: 700,
			clearCount: 5,
			frameX: 0,
			frameY: 350,
			offer: null,
			ballStandardSpeedY: -600,
			maxVelocityY: 1200,
		},
	};
};