BasicGame={
	GAME_TITLE:document.title,
	GAME_EN_TITLE:'',
	MAIN_COLOR:'#c8f7f4',//TODO
	MAIN_TINT:0xc8f7f4,//TODO
	MAIN_TEXT_COLOR:'#28ceff',//TODO
	MAIN_STROKE_COLOR:'#7ed0e6',//TODO
	WHITE_COLOR:'#e9f0f4',//TODO
	YOUTUBE_URL_1:'',//TODO
	YOUTUBE_URL_2:'',//TODO
	TW_URL:'',//TODO
};
BasicGame.Boot=function(){};
BasicGame.Boot.prototype={
init:function(){this.M.BootInit(!1)},
preload:function(){this.load.atlasJSONHash('loading','images/loading/loading.png','images/loading/loading.json')},
create:function(){
	this.M.dGlb({
		endTut:!1,
		playCount:0,
		curLang:'jp',
		// curLang:(this.M.H.getQuery('lang')=='en')?'en':'jp',
		Words:this.genWords(),
	});
	this.M.NextScene('Preloader');
},};