BasicGame.Boot.prototype.genCharInfo=function(){
	return {
		1:{
			charName:'おめがレイ',
			ytUrl:'https://www.youtube.com/channel/UCNjTjd2-PMC8Oo_-dCEss7A',
			ch:'Channel',chPath:'images/Nekomiya/Channel.png',
		},
		2:{
			charName:'おめがリオ',
			ytUrl:'https://www.youtube.com/channel/UCNjTjd2-PMC8Oo_-dCEss7A',
			ch:'Channel',chPath:'images/Nekomiya/Channel.png',
		},
		3:{
			charName:'おめがレリオ',
			ytUrl:'https://www.youtube.com/channel/UCNjTjd2-PMC8Oo_-dCEss7A',
			ch:'Channel',chPath:'images/Nekomiya/Channel.png',
		},
		4:{
			charName:'Icotsu',
			ytUrl:'https://www.youtube.com/channel/UCGFD_8TRHhlpjfqGhLUSk4g',
			ch:'Channel',chPath:'images/Nekomiya/Channel.png',
		},
		5:{
			charName:'法要通夜',
			ytUrl:'https://www.youtube.com/channel/UCGFD_8TRHhlpjfqGhLUSk4g',
			ch:'Channel',chPath:'images/Nekomiya/Channel.png',
		},
		6:{
			charName:'届木ウカ',
			ytUrl:'https://www.youtube.com/channel/UCk0dNVAdlgn4ynURwAq_z2A',
			ch:'Channel',chPath:'images/Nekomiya/Channel.png',
		},
		7:{
			charName:'女神エルミナ',
			ytUrl:'https://www.youtube.com/channel/UCGu_Yfe0HiMV4ffHvkVd9Jg',
			ch:'Channel',chPath:'images/Nekomiya/Channel.png',
		},
		8:{
			charName:'動く城のフィオ',
			ytUrl:'https://www.youtube.com/channel/UCiJr4MX-DrlKgLYC0luCjpQ',
			ch:'Channel',chPath:'images/Nekomiya/Channel.png',
		},
		9:{
			charName:'世界クルミ',
			ytUrl:'https://www.youtube.com/channel/UCHooCsg7FEVBGVKUE_RR0DA',
			ch:'Channel',chPath:'images/Nekomiya/Channel.png',
		},
		10:{
			charName:'雪猫カゥル',
			ytUrl:'https://www.youtube.com/channel/UCqlbdk8XtMSxogRDNMzRrxA',
			ch:'Channel',chPath:'images/Nekomiya/Channel.png',
		},
		11:{
			charName:'パンディ',
			ytUrl:'https://www.youtube.com/channel/UCu5DbFfYe3KiwhcmanCvSVg',
			ch:'Channel',chPath:'images/Nekomiya/Channel.png',
		},
		12:{
			charName:'クーテトラ',
			ytUrl:'https://www.youtube.com/channel/UCTqV6u2RJE4DqfLALsGuyAw',
			ch:'Channel',chPath:'images/Nekomiya/Channel.png',
		},
		13:{
			charName:'小山内めい',
			ytUrl:'https://www.youtube.com/channel/UCZx7wgGNs2UFyRRtLoNur9Q',
			ch:'Channel',chPath:'images/Nekomiya/Channel.png',
		},
		14:{
			charName:'虹乃まほろ',
			ytUrl:'https://www.youtube.com/channel/UCtCXaX0zEvYSgdkp-Po24TQ',
			ch:'Channel',chPath:'images/Nekomiya/Channel.png',
		},
		15:{
			charName:'勇者ことね',
			ytUrl:'https://www.youtube.com/channel/UCHR0kaG6d7eU1wm17fx9Mvw',
			ch:'Channel',chPath:'images/Nekomiya/Channel.png',
		},
		16:{
			charName:'公野ゆめか',
			ytUrl:'https://www.youtube.com/channel/UCMXKL1LgqMILqdavdc0DtVQ',
			ch:'Channel',chPath:'images/Nekomiya/Channel.png',
		},
	};
};
BasicGame.Boot.prototype.genStageInfo=function(){
	return {
		1:{
			selectorName:'広場',
			selectorSubName:'Lv.1',
			goalCount:5,
			isEndless:!1,
			dmge:10,
			firstChallengeCount:1,
		},
		2:{
			selectorName:'荒野',
			selectorSubName:'Lv.2',
			goalCount:6,
			isEndless:!1,
			dmge:20,
			firstChallengeCount:2,
		},
		3:{
			selectorName:'ビーチ',
			selectorSubName:'Lv.3',
			goalCount:7,
			isEndless:!1,
			dmge:30,
			firstChallengeCount:3,
		},
		4:{
			selectorName:'雪原',
			selectorSubName:'Lv.4',
			goalCount:10,
			isEndless:!1,
			dmge:40,
			firstChallengeCount:4,
		},
		5:{
			selectorName:'森',
			selectorSubName:'Lv.5',
			goalCount:15,
			isEndless:!1,
			dmge:80,
			firstChallengeCount:5,
		},
		6:{
			selectorName:'平野',
			selectorSubName:'コマンダー',
			goalCount:999,
			isEndless:!0,
			dmge:100,
			firstChallengeCount:1,
		},
	};
};