BasicGame.Boot.prototype.genCharInfo=function(){
	return {
		1:{
			charName:'AAAAAAAA',
			charIntro:'Peanutkun_Face',charIntroPath:'images/PeanutNinja/Peanutkun_Face.png',
			charSquare:'GuardHinako',charSquarePath:'images/Kerin/GuardHinako.png',
			idle:'Kikunojo',idlePath:'images/AoiGame/Hiyoko.png',
			animBase:'album_',animBasePath:'images/AzlimBushi/album_',
			ytUrl:'#',
			ch:'Channel',chPath:'images/Nekomiya/Channel.png',
		},
		2:{
			charName:'BBBBBBBB',
			charIntro:'Hiyoko',charIntroPath:'images/AoiGame/Kikunojo.png',
			charSquare:'GuardKaede',charSquarePath:'images/Kerin/GuardKaede.png',
			idle:'KerinOnMissile',idlePath:'images/Kerin/KerinOnMissile.png',
			animBase:'Album_',animBasePath:'images/HimeTanaka/Album_',
			ytUrl:'#',
			ch:'Channel',chPath:'images/Nekomiya/Channel.png',
		},
	};
};
BasicGame.Boot.prototype.genStageInfo=function(){
	// TODO 8 stg ???
	return {
		1:{
			selectorName:'CCCCCC',
			selectorSubName:'Lv.1',
			selector:'Clay',selectorPath:'images/Nekomiya/Clay.png',
			stgBg:'Bg_2',stgBgPath:'images/Nekomiya/Bg_2.jpg',
			goalCount:5,
			isEndless:!1,
			dmge:10,
			firstChallengeCount:1,
		},
		2:{
			selectorName:'DDDDDD',
			selectorSubName:'Lv.2',
			selector:'Clay',selectorPath:'images/Nekomiya/Clay.png',
			stgBg:'Bg_3',stgBgPath:'images/Nekomiya/Bg_3.jpg',
			goalCount:8,
			isEndless:!1,
			dmge:20,
			firstChallengeCount:3,
		},
		3:{
			selectorName:'EEEE',
			selectorSubName:'Lv.3',
			selector:'Clay',selectorPath:'images/Nekomiya/Clay.png',
			stgBg:'Bg_4',stgBgPath:'images/Nekomiya/Bg_4.jpg',
			goalCount:10,
			isEndless:!1,
			dmge:25,
			firstChallengeCount:5,
		},
		4:{
			selectorName:'FFFFFFFFF',
			selectorSubName:'ｺﾏﾝﾀﾞｰ',
			selector:'Clay',selectorPath:'images/Nekomiya/Clay.png',
			stgBg:'Bg_5',stgBgPath:'images/Nekomiya/Bg_5.jpg',
			goalCount:999,
			isEndless:!0,
			dmge:100,
			firstChallengeCount:1,
		},
		5:{
			selectorName:'FFFFFFFFF',
			selectorSubName:'ｺﾏﾝﾀﾞｰ',
			selector:'Clay',selectorPath:'images/Nekomiya/Clay.png',
			stgBg:'Bg_5',stgBgPath:'images/Nekomiya/Bg_5.jpg',
			goalCount:999,
			isEndless:!0,
			dmge:100,
			firstChallengeCount:1,
		},
		6:{
			selectorName:'FFFFFFFFF',
			selectorSubName:'ｺﾏﾝﾀﾞｰ',
			selector:'Clay',selectorPath:'images/Nekomiya/Clay.png',
			stgBg:'Bg_5',stgBgPath:'images/Nekomiya/Bg_5.jpg',
			goalCount:999,
			isEndless:!0,
			dmge:100,
			firstChallengeCount:1,
		},
	};
};