BasicGame.Boot.prototype.genCharInfo=function(){
	return {
		/////////// 0
		1:{cName:'ときのそら',open:!0,emoji:'(๑╹ᆺ╹)✨',
			scoreRate:1.5,addRespawnCount:0,playerSpeed:-700,reviveInterval:700,appearItemInterval:3E3,
			tw:'https://twitter.com/tokino_sora',
			yt:'https://www.youtube.com/channel/UCp6993wxpyDPHUpavwDFqgg',},
		2:{cName:'ロボ子',open:!0,emoji:'🤖🤖🤖🤖🤖🤖',
			scoreRate:1.2,addRespawnCount:1,playerSpeed:-500,reviveInterval:700,appearItemInterval:3E3,
			tw:'https://twitter.com/robocosan',
			yt:'https://www.youtube.com/channel/UCDqI2jOz0weumE8s7paEk6g',},
		3:{cName:'友人A',open:!0,emoji:'🅰️🅰️🅰️🅰️🅰️🅰️',
			scoreRate:1,addRespawnCount:0,playerSpeed:-600,reviveInterval:700,appearItemInterval:2E3,
			tw:null,
			yt:null,},
		4:{cName:'あん肝',open:!0,emoji:'🐻🐻🐻🐻🐻🐻',
			scoreRate:.8,addRespawnCount:0,playerSpeed:-600,reviveInterval:700,appearItemInterval:500,
			tw:'https://twitter.com/ankimoch',
			yt:'https://www.youtube.com/channel/UCGSOfFtVCTBfmGxHK5OD8ag',},
		5:{cName:'ホロライブ',open:!1,emoji:'▶️▶️▶️▶️▶️▶️',
			scoreRate:.3,addRespawnCount:3,playerSpeed:-900,reviveInterval:400,appearItemInterval:500,
			tw:'https://twitter.com/hololivetv',
			yt:'https://www.hololive.tv/',},
		/////////// 1
		6:{cName:'夜空メル',open:!0,emoji:'🌟🌟🌟🌟🌟🌟',
			scoreRate:1.2,addRespawnCount:2,playerSpeed:-450,reviveInterval:500,appearItemInterval:5E3,
			tw:'https://twitter.com/yozoramel',
			yt:'https://www.youtube.com/channel/UCD8HOxPs4Xvsm8H0ZxXGiBw',},
		7:{cName:'アキ・ローゼンタール',open:!0,emoji:'🍎🍎🍎🍎🍎🍎',
			scoreRate:1.5,addRespawnCount:0,playerSpeed:-600,reviveInterval:800,appearItemInterval:2E3,
			tw:'https://twitter.com/akirosenthal',
			yt:'https://www.youtube.com/channel/UCFTLzh12_nrtzqBPsTCqenA',},
		8:{cName:'赤井はあと',open:!0,emoji:'❤️❤️❤️❤️❤️❤️',
			scoreRate:1.3,addRespawnCount:1,playerSpeed:-800,reviveInterval:800,appearItemInterval:3E3,
			tw:'https://twitter.com/akaihaato',
			yt:'https://www.youtube.com/channel/UC1CfXB_kRs3C-zaeTG3oGyg',},
		9:{cName:'白上フブキ',open:!0,emoji:'🌽🌽🌽🌽🌽🌽',
			scoreRate:1,addRespawnCount:1,playerSpeed:-600,reviveInterval:700,appearItemInterval:500,
			tw:'https://twitter.com/shirakamifubuki',
			yt:'https://www.youtube.com/channel/UCdn5BQ06XqgXoAxIhbqw5Rg',},
		10:{cName:'夏色まつり',open:!0,emoji:'🏮🏮🏮🏮🏮🏮',
			scoreRate:1.1,addRespawnCount:3,playerSpeed:-700,reviveInterval:600,appearItemInterval:2E3,
			tw:'https://twitter.com/natsuiromatsuri',
			yt:'https://www.youtube.com/channel/UCQ0UDLQCjY0rmuxCDE38FGg',},
		/////////// 2
		11:{cName:'湊あくあ',open:!0,emoji:'⚓️⚓️⚓️⚓️⚓️⚓️',
			scoreRate:.8,addRespawnCount:2,playerSpeed:-800,reviveInterval:500,appearItemInterval:2E3,
			tw:'https://twitter.com/minatoaqua',
			yt:'https://www.youtube.com/channel/UC1opHUrw8rvnsadT-iGp7Cg',},
		12:{cName:'紫咲シオン',open:!0,emoji:'🌙🌙🌙🌙🌙🌙',
			scoreRate:.9,addRespawnCount:1,playerSpeed:-400,reviveInterval:500,appearItemInterval:2E3,
			tw:'https://twitter.com/murasakishionch',
			yt:'https://www.youtube.com/channel/UCXTpFs_3PqI41qX2d9tL2Rw',},
		13:{cName:'百鬼あやめ',open:!0,emoji:'😈😈😈😈😈😈',
			scoreRate:1.3,addRespawnCount:0,playerSpeed:-500,reviveInterval:600,appearItemInterval:3E3,
			tw:'https://twitter.com/nakiriayame',
			yt:'https://www.youtube.com/channel/UC7fk0CB07ly8oSl0aqKkqFg',},
		14:{cName:'癒月ちょこ',open:!0,emoji:'💋💋💋💋💋💋',
			scoreRate:1.3,addRespawnCount:0,playerSpeed:-700,reviveInterval:700,appearItemInterval:1E3,
			tw:'https://twitter.com/yuzukichococh',
			yt:'https://www.youtube.com/channel/UC1suqwovbL1kzsoaZgFZLKg',},
		15:{cName:'大空スバル',open:!0,emoji:'🚑🚑🚑🚑🚑🚑',
			scoreRate:1,addRespawnCount:1,playerSpeed:-600,reviveInterval:400,appearItemInterval:4E3,
			tw:'https://twitter.com/oozorasubaru',
			yt:'https://www.youtube.com/channel/UCvzGlP9oQwU--Y0r9id_jnA',},
	};
};
BasicGame.Boot.prototype.genLevelInfo=function(){
	return {
		1:{leftTime:120,timeAttack:!1,targetScore:10000,respawnCount:0,respawnInterval:800,targetMoveSpeedMin:100,},
		2:{leftTime:120,timeAttack:!1,targetScore:30000,respawnCount:0,respawnInterval:800,targetMoveSpeedMin:100,},
		3:{leftTime:100,timeAttack:!1,targetScore:40000,respawnCount:0,respawnInterval:650,targetMoveSpeedMin:150,},
		4:{leftTime:100,timeAttack:!1,targetScore:80000,respawnCount:1,respawnInterval:650,targetMoveSpeedMin:150,},
		5:{leftTime:80,timeAttack:!1,targetScore:100000,respawnCount:1,respawnInterval:500,targetMoveSpeedMin:200,},
		6:{leftTime:80,timeAttack:!1,targetScore:200000,respawnCount:1,respawnInterval:500,targetMoveSpeedMin:200,},
		7:{leftTime:60,timeAttack:!0,targetScore:null,respawnCount:0,respawnInterval:500,targetMoveSpeedMin:150,},
		8:{leftTime:120,timeAttack:!0,targetScore:null,respawnCount:1,respawnInterval:500,targetMoveSpeedMin:150,},
	};
};
BasicGame.Boot.prototype.genWords=function(){
	var touchJP=this.M.gGlb('TOUCH_OR_CLICK');
	////// var touchEN=this.M.gGlb('EN_TOUCH_OR_CLICK');
	return {
		jp:{
			Start:'スタート',
			ToTitle:'タイトルへ',
			Back:'もどる',
			Score:'スコア: ',
			LeftTime:'制限時間: ',
			Clear:'クリア！',
			NotClear:'残念！',
			GameOver:'ゲームオーバー！',
			HowTo:'遊び方\n\n画面を'+touchJP+'して\n選択したメンバーを\n飛ばそう！\nメンバーに当てると\nスコアアップ！\n目標達成でクリア！\nはずすとスコアが減るよ\nホロライブアイテムを\nうまく使って\n高得点を狙え！',
			Result:'結果',
			ResScore:'スコア\n',
			Again:'もう一度',
			NextLevel:'次のレベルへ',
			TwBtn:'結果をツイート',
			OtherGames:'他のゲーム',
			TwTtl:'『'+BasicGame.GAME_TITLE+'』で遊んだよ！',
			TwHT:'ホロライブゲーム',
			TimeUp:'タイムアップ！',
			TimeAttack:'タイムアタック',
			SelectChar:'メンバーを選択',
			SelectLevel:'レベルを選択',
			TwSelectChar:'選んだメンバー: ',
			TwRes:'結果: ',
			TwLevel:'挑戦したレベル: ',
			Ability_0:'貫通',
			Ability_1:'スコア＋',
			Ability_2:'タイム＋',
			Ability_3:'速',
			Ability_4:'遅',
			TargetScore:'目標: ',
		},
		en:{
		},
	};
};