BasicGame.Boot.prototype.genCharInfo=function(){
	return {
		1:{cName:'もこ田めめめ',
			waveInterval:12,miniHard:12,jumpPower:18,scoreRate:1,itemInterval:15,itemSpeed:2E3,
			emoji:'🐏🐏🐏🐏🐏🐏',
			yt:'https://www.youtube.com/channel/UCz6Gi81kE6p5cdW1rT0ixqw',tw:'https://twitter.com/mokomeme_ch',},
		2:{cName:'花京院ちえり',
			waveInterval:8,miniHard:10,jumpPower:18,scoreRate:1.2,itemInterval:15,itemSpeed:1500,
			emoji:'🍒🍒🍒🍒🍒🍒',
			yt:'https://www.youtube.com/channel/UCP9ZgeIJ3Ri9En69R0kJc9Q',tw:'https://twitter.com/chieri_kakyoin',},
		3:{cName:'神楽すず',
			waveInterval:10,miniHard:5,jumpPower:18,scoreRate:1,itemInterval:13,itemSpeed:2E3,
			emoji:'🍋🍋🍋🍋🍋🍋',
			yt:'https://www.youtube.com/channel/UCUZ5AlC3rTlM-rA2cj5RP6w',tw:'https://twitter.com/kagura_suzu',},
		4:{cName:'金剛いろは',
			waveInterval:10,miniHard:10,jumpPower:23,scoreRate:1,itemInterval:15,itemSpeed:2E3,
			emoji:'💎💎💎💎💎💎',
			yt:'https://www.youtube.com/channel/UCiGcHHHT3kBB1IGOrv7f3qQ',tw:'https://twitter.com/KongoIroha',},
		5:{cName:'カルロピノ',
			waveInterval:10,miniHard:10,jumpPower:16,scoreRate:1.1,itemInterval:15,itemSpeed:2E3,
			emoji:'🐜🐜🐜🐜🐜🐜',
			yt:'https://www.youtube.com/channel/UCMzxQ58QL4NNbWghGymtHvw',tw:'https://twitter.com/carro_pino',},
		6:{cName:'牛巻りこ',
			waveInterval:10,miniHard:10,jumpPower:18,scoreRate:1,itemInterval:7,itemSpeed:1800,
			emoji:'🐮🐮🐮🐮🐮🐮',
			yt:'https://www.youtube.com/channel/UCKUcnaLsG2DeQqza8zRXHiA',tw:'https://twitter.com/UshimakiRiko',},
		7:{cName:'夜桜たま',
			waveInterval:11,miniHard:8,jumpPower:18,scoreRate:1,itemInterval:15,itemSpeed:3E3,
			emoji:'🌸🌸🌸🌸🌸🌸',
			yt:'https://www.youtube.com/channel/UCOefINa2_BmpuX4BbHjdk9A',tw:'https://twitter.com/YozakuraTama',},
		8:{cName:'木曽あずき',
			waveInterval:15,miniHard:9,jumpPower:13,scoreRate:.8,itemInterval:13,itemSpeed:2E3,
			emoji:'🍡🐛🍡🐛🍡🐛',
			yt:'https://www.youtube.com/channel/UCmM5LprTu6-mSlIiRNkiXYg',tw:'https://twitter.com/KisoAzuki',},
		9:{cName:'北上双葉',
			waveInterval:10,miniHard:10,jumpPower:20,scoreRate:1.1,itemInterval:15,itemSpeed:2E3,
			emoji:'🌱🌱🌱🌱🌱🌱',
			yt:'https://www.youtube.com/channel/UC5nfcGkOAm3JwfPvJvzplHg',tw:'https://twitter.com/KitakamiFutaba',},
		10:{cName:'猫乃木もち',
			waveInterval:11,miniHard:9,jumpPower:18,scoreRate:1,itemInterval:15,itemSpeed:3E3,
			emoji:'🐈🐈🐈🐈🐈🐈',
			yt:'https://www.youtube.com/channel/UC02LBsjt_Ehe7k0CuiNC6RQ',tw:'https://twitter.com/nekonoki_mochi',},
		11:{cName:'ヤマトイオリ',
			waveInterval:9,miniHard:12,jumpPower:18,scoreRate:1.1,itemInterval:15,itemSpeed:1600,
			emoji:'🎀🎀🎀🎀🎀🎀',
			yt:'https://www.youtube.com/channel/UCyb-cllCkMREr9de-hoiDrg',tw:'https://twitter.com/YamatoIori',},
		12:{cName:'八重沢なとり',
			waveInterval:9,miniHard:11,jumpPower:16,scoreRate:1.5,itemInterval:15,itemSpeed:1E3,
			emoji:'🌾🌾🌾🌾🌾🌾',
			yt:'https://www.youtube.com/channel/UC1519-d1jzGiL1MPTxEdtSA',tw:'https://twitter.com/YaezawaNatori',},
	};
};
BasicGame.Boot.prototype.genWords=function(){
	var touchJP=this.M.gGlb('TOUCH_OR_CLICK');
	////// var touchEN=this.M.gGlb('EN_TOUCH_OR_CLICK');
	return {
		jp:{
			Start:'スタート',
			Score:'スコア: ',
			WaveTime:'リスポーンまで: ',
			Result:'結果',
			Back:'もどる',
			ResScore:'スコア\n',
			Again:'もう一度',
			TwBtn:'結果をツイート',
			OtherGames:'他のゲーム',
			SelectChar:'メンバーを選択',
			End:'終了～！',
			Endless:'< エンドレスモード >',
			HowTo:'＜ 遊び方 ＞\nアイドル部のメンバーを\n赤線の下に来たときに\n'+touchJP+'して\nスコアをかせごう！\n下のトゲに当たると終了。\n時間が経つと\nメンバーが追加！\nシロちゃんとばあちゃるを\n'+touchJP+'すると\nスコアアップ！\n目指せハイスコア！',
			TwTtl:'『'+BasicGame.GAME_TITLE+'』で遊んだよ！',
			TwHT:'ドットライブゲーム',
			TwSelectChar:'選んだメンバー: ',
			ScoreDoubleFront:'ウビバ！スコア',
			ScoreTripleFront:'おほー！スコア',
			ScoreUpBack:'倍！',
		},
		en:{
		},
	};
};