BasicGame.Boot.prototype.genCharInfo=function(){
	return {
		1:{cId:1,color:'#fc87a4',cName:'キズナアイ',yt:'https://www.youtube.com/channel/UC4YaOt1yT-ZeyB0OmxHgolA',},
		2:{cId:2,color:'#3e9283',cName:'YuNi',yt:'https://www.youtube.com/channel/UCHTnX0CSX_KObo5I9WuZ64g',},
		3:{cId:3,color:'#de7071',cName:'おめがシスターズ',yt:'https://www.youtube.com/channel/UCNjTjd2-PMC8Oo_-dCEss7A',},
		4:{cId:4,color:'#feaec9',cName:'織田信姫',yt:'https://www.youtube.com/channel/UCGcD5iUDG8xiywZeeDxye-A',},
		5:{cId:5,color:'#e3c390',cName:'因幡はねる',yt:'https://www.youtube.com/channel/UC0Owc36U9lOyi9Gx9Ic-4qg/',},
		6:{cId:6,color:'#f0c3e0',cName:'宇森ひなこ',yt:'https://www.youtube.com/channel/UChqYnJlFxlBi6DfRz6jRenQ',},
		7:{cId:7,color:'#5cbbf3',cName:'宗谷いちか',yt:'https://www.youtube.com/channel/UC2kyQhzGOB-JPgcQX9OMgEw',},
		8:{cId:8,color:'#add167',cName:'日ノ隈らん',yt:'https://www.youtube.com/channel/UCRvpMpzAXBRKJQuk-8-Sdvg',},
		9:{cId:9,color:'#D73637',cName:'稲荷くろむ',yt:'https://www.youtube.com/channel/UCGiFzwdasSAHILrx-DB1pVQ',},
		10:{cId:10,color:'#e78a94',cName:'周防パトラ',yt:'https://www.youtube.com/channel/UCeLzT-7b2PBcunJplmWtoDg',},
		11:{cId:11,color:'#7454b5',cName:'蒼月エリ',yt:'https://www.youtube.com/channel/UC3UKMRQmBcjXWu66cvxcngA',},
		12:{cId:12,color:'#345AA1',cName:'島村シャルロット',yt:'https://www.youtube.com/channel/UCYTz3uIgwVY3ZU-IQJS8r3A',},
		13:{cId:13,color:'#d8c3dc',cName:'西園寺メアリ',yt:'https://www.youtube.com/channel/UCwePpiw1ocZRSNSkpKvVISw',},
		14:{cId:14,color:'#b0b798',cName:'堰代ミコ',yt:'https://www.youtube.com/channel/UCDh2bWI5EDu7PavqwICkVpA',},
		15:{cId:15,color:'#5467c6',cName:'塩天使リエル',yt:'https://www.youtube.com/channel/UCE5rWcDxLPaaUFWOxzJFfNg',},
		16:{cId:16,color:'#a0cdca',cName:'戸越ぷらむ',yt:'https://www.youtube.com/channel/UCk7cMvrfvH98Bfng58N_Zzw',},
		17:{cId:17,color:'#DD1408',cName:'由宇霧',yt:'https://www.youtube.com/channel/UCMxKcUjeTEcgHmC9Zzn3R4w',},
		18:{cId:18,color:'#b787cf',cName:'きらめる',yt:'https://www.youtube.com/channel/UCNs8PbeYTpX6eYghsBGR_qA',},
		19:{cId:19,color:'#d44897',cName:'イア',yt:'https://www.youtube.com/channel/UCwaHfjz_FDvQPsSRsbgtxGQ',},
		20:{cId:20,color:'#1f4e9d',cName:'チェリ高帰宅部',yt:'https://www.youtube.com/channel/UCBnJcqkJofBN26VELPXSB5A',},
		21:{cId:21,color:'#d1bfcf',cName:'のらきゃっと',yt:'https://www.youtube.com/channel/UC3iwL9Yz8LcKkJsnLPevOTQ',},
		22:{cId:22,color:'#ecad12',cName:'かしこまり',yt:'https://www.youtube.com/channel/UCfiK42sBHraMBK6eNWtsy7A',},
		23:{cId:23,color:'#b8efb6',cName:'虹河ラキ',yt:'https://www.youtube.com/channel/UCp77Qho-YHhnklRr-DkjiOw',},
		24:{cId:24,color:'#e8a070',cName:'カフェ野ゾンビ子',yt:'https://www.youtube.com/channel/UCiVRnULJjc8o-j_lG5BAzKw',},
		25:{cId:25,color:'#ffb9d3',cName:'響木アオ',yt:'https://www.youtube.com/c/HibikiAo',},
		26:{cId:26,color:'#ff0036',cName:'小山内めい',yt:'https://www.youtube.com/channel/UCZx7wgGNs2UFyRRtLoNur9Q',},
		27:{cId:27,color:'#c07fd3',cName:'春日部つくし',yt:'https://www.youtube.com/channel/UCHccxX2p_9DB_HPnXSb2omw',},
		28:{cId:28,color:'#7bb3e2',cName:'海月ねう',yt:'https://www.youtube.com/channel/UCLXxry0HqEz_mzHSsXwrhYg',},
		29:{cId:29,color:'#ec797e',cName:'つのはねあかぎ',yt:'https://www.youtube.com/user/misakiakagi',},
		30:{cId:30,color:'#eaad05',cName:'ぽてち',yt:'https://www.youtube.com/channel/UCPljC4d-GgdFgVqtoCZ3m_w',},
		31:{cId:31,color:'#7c543a',cName:'モスコミュール',yt:'https://www.youtube.com/channel/UCX7WYPXASkYUm2GyomLllIg',},
		32:{cId:32,color:'#8bd1cf',cName:'デラとハドウ',yt:'https://www.youtube.com/channel/UC0QzO6nK1cEDZvJSt2769Zw',},
		33:{cId:33,color:'#ffe876',cName:'パンディ',yt:'https://www.youtube.com/channel/UCu5DbFfYe3KiwhcmanCvSVg',},
		34:{cId:34,color:'#fe8113',cName:'天音マホ',yt:'https://www.youtube.com/channel/UCH9DjwkMq9P6yGioc0-NaJg',},
		35:{cId:35,color:'#e26493',cName:'音無りずむ',yt:'https://www.youtube.com/channel/UCJzg5k2prEhTPMoK0kcBQPg',},
		36:{cId:36,color:'#afe8f3',cName:'エンジンかずみ',yt:'https://www.youtube.com/channel/UCZk6mxfTpjuuxgqxuFBJO_g',},
		37:{cId:37,color:'#e5877f',cName:'空(KON)@K\'WA',yt:'https://www.youtube.com/channel/UCyZZMKRn-mUEkPzaqa9b6bg',},
		38:{cId:38,color:'#e0ae89',cName:'AyaMina Games',yt:'https://www.youtube.com/channel/UCrSpZbNNao8YQ5aj2Jr2exw',},
		39:{cId:39,color:'#b7ada3',cName:'佐々木',yt:'https://www.youtube.com/channel/UCa8OnR-Qm9-h9yOZaMyShpg',firstName:'内務省エージェントプログラム',},
		40:{cId:40,color:'#e1caa1',cName:'ゴルンノヴァ総統',yt:'https://www.youtube.com/channel/UCc32jRyXfJBSZg9_EDXceTA',},
		41:{cId:41,color:'#8D5FCD',cName:'けも神男子',yt:'https://www.youtube.com/channel/UCs8xsWmWEjjcyjAFu5KMGIg',},
	};
};
BasicGame.Boot.prototype.genWords=function(){
	// var a=this.M.gGlb('TOUCH_OR_CLICK');
	// var b=this.M.gGlb('EN_TOUCH_OR_CLICK');
	return {
		jp:{
			Start:'スタート',
			FalseCards:'お手つき！',
			TweetTtl:'『'+BasicGame.GAME_TITLE+'』で遊んだよ！',
			TweetFirstGotCard:'最初にゲットしたVtuber: \n',
			TweetFalseCount:'お手つき: ',
			TweetClearTime:'クリアタイム: ',
			TweetHT:'upd8ゲーム',
			// Back:'もどる',
			// HowTo:'41人いるupd8のメンバーで神経衰弱！\n同じVtuberを'+a+'引き当てよう！',
			// Clear:'クリア！',
			// Result:'結果',
			// Again:'もういちど',
			// OtherGames:'他のゲーム',
			// Tweet:'結果をツイート',
			// TweetRes:'',
		},
		en:{},//TODO
	};
};