BasicGame={
	GAME_TITLE:document.title,
	GAME_TITLE_EN:document.title,
	MAIN_COLOR:'#cbd7ea',
	MAIN_TINT:0xcbd7ea,
	MAIN_TEXT_COLOR:'#f62018',
	MAIN_STROKE_COLOR:'#f62018',
	WHITE_COLOR:'#fbf0ee',
	YOUTUBE_URL:'https://www.youtube.com/channel/UCZx7wgGNs2UFyRRtLoNur9Q',
};
BasicGame.Boot=function(){};
BasicGame.Boot.prototype={
init:function(){this.M.BootInit(!1)},
preload:function(){this.load.atlasJSONHash('loading','images/loading/loading.png','images/loading/loading.json')},
create:function(){
	this.M.dGlb({
		curLang:(this.M.H.getQuery('lang')=='en')?'en':'jp',
		playCount:0,
		endTut:!1,
		curStg:1,
		totalToFCount:0,
		Words:this.genWords(),
		StageInfo:this.genStageInfo(),
	});
	this.M.NextScene('Preloader');
},};