BasicGame={
	GAME_TITLE:document.title,
	GAME_TITLE_EN:'',
	MAIN_COLOR:'#48468f',
	MAIN_TINT:0x48468f,
	MAIN_TEXT_COLOR:'#302e31',
	MAIN_STROKE_COLOR:'#302e31',
	WHITE_COLOR:'#f6f4f5',
	YOUTUBE_URL:'https://www.youtube.com/channel/UCD-miitqNY3nyukJ4Fnf4_A',
	MY_GAMES_URL:'https://238g.github.io/Parace/238Games.html',
};
BasicGame.Boot=function(){};
BasicGame.Boot.prototype={
init:function(){this.M.BootInit(!1);},
preload:function(){this.load.crossOrigin='Anonymous';this.load.atlasJSONHash('loading','images/loading/loading.png','images/loading/loading.json');},
create:function(){
	this.M.dGlb({
		curLang:'jp',
		playCount:0,
		// curLang:(this.M.H.getQuery('lang')=='en')?'en':'jp',
		Words:this.genWords(),
		curStage:1,
		endTut:!1,
		StageInfo:this.genStageInfo(),
	});
	this.M.NextScene('Preloader');
},};